name: Deploy to GKE

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest # Use a GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker authentication
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/forex-repo/forex-cpp-service:latest .
          docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/forex-repo/forex-cpp-service:latest

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials forex-cpp-cluster --zone=us-central1-a
          kubectl apply -f deployment.yaml
        env:
          CLOUDSDK_COMPUTE_ZONE: us-central1-a
          CLOUDSDK_CONTAINER_CLUSTER: forex-cpp-cluster
